---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

# title: "Homer"
# subtitle: ""
# logo: "assets/logo.png"
# icon: ""

# Optional message
# See https://bulma.io/documentation/components/message/#colors for styling options.
# message:
#   style: "is-warning"
#   title: "Optional message!"
#   content: "Lorem ipsum dolor sit amet."

# # Optional navbar
# links:
#   - name: "Email"
#     icon: []
#     url: "mailto:ch@chasehall.net"
#   - name: "Snapchat"
#     icon: []
#     url: "https://snapchat.com/add/chaser780"
#   - name: "GitHub"
#     icon: []
#     url: "https://github.com/ChaseHall"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Services"
    icon: []
    items:
      - name: "qBittorrent"
        logo: "assets/tools/qbit.png"
        subtitle: "Admin UI for Torrents"
        tag: ""
        url: "http://127.0.0.1:8080"
  - name: "Plex"
    icon: []
    items:
      - name: "Plex"
        logo: "assets/tools/plex.png"
        subtitle: "Plex Media Server Frontend"
        tag: ""
        url: "http://127.0.0.1:32400/web/index.html"
      - name: "Sonarr"
        logo: "assets/tools/sonarr.jpg"
        subtitle: "Automatically download TV Shows for Plex"
        tag: ""
        url: "http://localhost:8989/"
      - name: "Radarr"
        logo: "assets/tools/radarr.png"
        subtitle: "Automatically download Movies for Plex"
        tag: ""
        url: "http://localhost:7878/"
      - name: "Jackett"
        logo: "assets/tools/jackett.png"
        subtitle: "Manage trackers for Sonarr + Radarr"
        tag: ""
        url: "http://localhost:9117/"
