---
services:
  - name: "Section 1"
    icon: []
    items:
      - name: "Service 1"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flat_tick_icon.svg/1200px-Flat_tick_icon.svg.png"
        subtitle: "Lorem ipsum dolor sit amet."
        tag: ""
        url: "https://domain.tld"
      - name: "Service 2"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flat_tick_icon.svg/1200px-Flat_tick_icon.svg.png"
        subtitle: "Lorem ipsum dolor sit amet."
        tag: ""
        url: "https://subdomain.domain.tld"
      - name: "Service 3"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flat_tick_icon.svg/1200px-Flat_tick_icon.svg.png"
        subtitle: "Lorem ipsum dolor sit amet."
        tag: ""
        url: "https://sub.domain.tld/page"
  - name: "Plex"
    icon: []
    items:
      - name: "Service 1"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flat_tick_icon.svg/1200px-Flat_tick_icon.svg.png"
        subtitle: "Lorem ipsum dolor sit amet."
        tag: ""
        url: "https://domain.tld"
      - name: "Service 2"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flat_tick_icon.svg/1200px-Flat_tick_icon.svg.png"
        subtitle: "Lorem ipsum dolor sit amet."
        tag: ""
        url: "https://subdomain.domain.tld"
      - name: "Service 3"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flat_tick_icon.svg/1200px-Flat_tick_icon.svg.png"
        subtitle: "Lorem ipsum dolor sit amet."
        tag: ""
        url: "https://sub.domain.tld/page"
